### ISSUE TITLE
error when running finnegan

### ISSUE THREAD

**Issue by miklos-szel** [gurushida/finnegan#1]
I get the following error when trying to runt `finnegan en.json`:
`error: TS2345 [ERROR]: Argument of type '9' is not assignable to parameter of type 'Signal'.
            this.fartProcess.kill(9);`

I also get the same error when remove --unstable:
`deno run   --import-map import_map.json --allow-read --allow-run  --allow-net src/main.ts $*
Check file:///xxxinnegan/src/main.ts
error: TS2345 [ERROR]: Argument of type '9' is not assignable to parameter of type 'Signal'.
            this.fartProcess.kill(9);
                                  ^
    at file:///xxx/finnegan/src/finnegan.ts:174:35`

Deno: stable 1.16.2 (bottled)
os: MacOs Big Sur: 11.6.1

**Comment by gurushida** [comment]
I developed this with Deno 1.9.0 which used a number argument for `kill`. It is now a `Signal` type that takes signal names. I have adjusted the code to the new values in commit https://github.com/gurushida/finnegan/commit/b59527df54aa61cc8f73337a78b04001e12c6ef4
